import { relativeTimeFormatter } from "../util-frontend";

export const monitorDefaults = {
    type: "http",
    name: "",
    parent: null,
    url: "https://",
    method: "GET",
    ipFamily: null,
    interval: 60,
    humanReadableInterval: relativeTimeFormatter.secondsToHumanReadableFormat(60),
    retryInterval: 60,
    resendInterval: 0,
    maxretries: 0,
    notificationIDList: {},
    ignoreTls: false,
    upsideDown: false,
    expiryNotification: false,
    maxredirects: 10,
    accepted_statuscodes: [ "200-299" ],
    dns_resolve_type: "A",
    dns_resolve_server: "1.1.1.1",
    docker_container: "",
    docker_host: null,
    proxyId: null,
    mqttUsername: "",
    mqttPassword: "",
    mqttTopic: "",
    mqttWebsocketPath: "",
    mqttSuccessMessage: "",
    mqttCheckType: "keyword",
    authMethod: null,
    oauth_auth_method: "client_secret_basic",
    httpBodyEncoding: "json",
    kafkaProducerBrokers: [],
    kafkaProducerSaslOptions: {
        mechanism: "None",
    },
    cacheBust: false,
    kafkaProducerSsl: false,
    kafkaProducerAllowAutoTopicCreation: false,
    gamedigGivenPortOnly: true,
    remote_browser: null,
    rabbitmqNodes: [],
    rabbitmqUsername: "",
    rabbitmqPassword: "",
    conditions: [],
};

export function createMonitorDefaults() {
    return {
        ...monitorDefaults,
        accepted_statuscodes: [ ...monitorDefaults.accepted_statuscodes ],
        notificationIDList: {},
        kafkaProducerBrokers: [],
        kafkaProducerSaslOptions: { ...monitorDefaults.kafkaProducerSaslOptions },
        rabbitmqNodes: [],
        conditions: [],
        ping_count: 3,
        ping_numeric: true,
        packetSize: 56,
        ping_per_request_timeout: 2,
    };
}
